replicaCount: 1
image:
  repository: artifactory-jcr.infra:30000/docker-local/com.optimagrowth/eureka-service
  pullPolicy: IfNotPresent
  tag: 0.0.1-SNAPSHOT@sha256:335dfda99e62e057cbdbe1b7a406aab53f4466f9370ab0bd2b016f83ea4d358f
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - curl -f -s localhost:8080/actuator/health/liveness | grep '{"status":"UP"}'
        || exit
  failureThreshold: 5
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - curl -f -s localhost:8080/actuator/health/readiness | grep '{"status":"UP"}'
        || exit
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_CLOUD_CONFIG_URI
    value: http://config-service:8080
