replicaCount: 1
image:
  repository: artifactory-jcr.infra:30000/docker-local/com.optimagrowth/organization-service
  pullPolicy: IfNotPresent
  tag: 0.0.1-SNAPSHOT@sha256:d0a8e0bf93ef4f0bae40c977df07c02d9d8cbeb995f528958fa635c7aaf6c091
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes:
  - name: organization-service
    secret:
      secretName: organization-service
volumeMounts:
  - name: organization-service
    mountPath: /run/secrets/jwt/issuer-uri
    readOnly: true
    subPath: jwt-issuer-uri
  - name: organization-service
    mountPath: /run/secrets/datasource/url
    readOnly: true
    subPath: datasource-url
  - name: organization-service
    mountPath: /run/secrets/datasource/username
    readOnly: true
    subPath: datasource-username
  - name: organization-service
    mountPath: /run/secrets/datasource/password
    readOnly: true
    subPath: datasource-password
nodeSelector: {}
tolerations: []
affinity: {}
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_CLOUD_CONFIG_URI
    value: http://config-service:8080
  - name: EUREKA_URI
    value: http://eureka-service:8080/eureka
  - name: JWT_ISSUER_URI_FILE
    value: /run/secrets/jwt/issuer-uri
  - name: DATASOURCE_URL_FILE
    value: /run/secrets/datasource/url
  - name: DATASOURCE_USERNAME_FILE
    value: /run/secrets/datasource/username
  - name: DATASOURCE_PASSWORD_FILE
    value: /run/secrets/datasource/password
